AWSTemplateFormatVersion: '2010-09-09'
Description: ALB Nested Stack - Internet-facing Application Load Balancer
Resources:
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/alb.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-0219d51cdf099f663 # Replace with actual VPC ID
        PublicSubnet1: subnet-0cfd97d93dcb38aff
        PublicSubnet2: subnet-0beccc540fd135816
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
