AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Nested Stack - ECS Cluster backed by EC2 ASG (t4g.small, min/max/desired=1)
Resources:
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecs-migration-cloud-formation-templates.s3.us-east-1.amazonaws.com/templates/ecs.yaml
      Parameters:
        Environment: dev
        VpcId: vpc-0219d51cdf099f663
        PrivateSubnet1: subnet-0cfd97d93dcb38aff
        PrivateSubnet2: subnet-0beccc540fd135816
        KeyPairName: dev-ecs-keypair
        InstanceType: t4g.small
        ALBSecurityGroup: sg-01f333a654dbac8f1
        ALBTargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:533267275979:listener/app/dev-alb/1376405deaecf4d1/51a678a003d78b46
        
      Tags:
        - Key: Environment
          Value: dev
        - Key: ManagedBy
          Value: CloudFormation
Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName

    
