AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch log group for application

Parameters:
  LogGroupName:
    Type: String
    Description: Name of the CloudWatch log group
  RetentionInDays:
    Type: Number
    Default: 30
    Description: Log retention in days

Resources:
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName
      RetentionInDays: !Ref RetentionInDays

Outputs:
  LogGroupName:
    Value: !Ref AppLogGroup
    Description: Name of the log group

  LogGroupArn:
    Value: !GetAtt AppLogGroup.Arn
    Description: ARN of the log group
