AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket Creation

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-simple-cloudformation-bucket-1202026
      VersioningConfiguration:
        Status: Enabled
        
Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket

  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
